### ISSUE TITLE
Change JSON data

### ISSUE THREAD

**Issue by petrberan** [jboss-set/build-trigger#29]
As we're moving away from triggering a build, we need to change the JSON we're sending to contain only the data that are necessary or the one we have access to, thus we need to:

- [ ] Move `email` one level up
- [ ] Remove `msg`
- [ ] Remove `project`
- [ ] Remove `script`
- [ ] Add `stream` - eap:7.3.x, eap:7.4.x, eap:8.0.x, eap-xp:4.0.x and eap-xp:5.0.x

**Comment by khermano** [comment]
@petrberan We are creating the JSON in the BuildTrigger class, where we can see that the BuildJMSTriggerPayload class is serialized as a String and sent as a message to the specified destination. So, the "msg" we see in the JSON is the message we are sending (BuildJMSTriggerPayload class), which is why the "msg" cannot be removed. 
For other data, they are attributes of the actual class BuildJMSTriggerPayload we are sending, so I would wait for https://github.com/jboss-set/build-trigger/issues/30 to see what I can and can't do. What do you think about this?
